version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  api:
    build: .
    ports:
      - 8080:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      DB_NAME: api-ts
      DB_URL: mongodb://mongo_db:27017
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
